Check MemberWorkingDays and SprintWorkingDays. Add attributes in _Wor…
epambrest/capacity pull request #140
Opened 2021-02-01 13:38 UTC by Y-floryanovich

…kingPartialView.
Add validation in order to check working days for member according to sprint days.

2021-02-01 16:28 UTC, desenzo requested changes

2021-02-01 16:28 UTC, desenzo commented on src/Teams.Web/Controllers/ManageMemberWorkingDaysController.cs
> +            var sprint = _manageSprintsService.GetSprintAsync(sprintId, false).Result;
await not Result

2021-02-03 12:05 UTC, desenzo approved these changes

2021-02-03 13:22 UTC, sub13 approved these changes

2021-02-03 13:25 UTC, halvita approved these changes

2021-02-04 14:52 UTC, merged