Create pushDockerToACR.yml
epambrest/capacity pull request #149
Opened 2021-02-11 13:50 UTC by sub13

I've created action to push our docker image to Azure Container Regestry. This action will work after 20-th Febrary, because our server isn't working now. If you noticed something wrong, please write down, also don't merge this pull request yet

2021-02-11 17:53 UTC, desenzo approved these changes

2021-02-12 11:24 UTC, SergeyMokin requested changes

2021-02-12 11:24 UTC, SergeyMokin commented on .github/workflows/pushDockerToACR.yml
> +    - name: Azure Service Principal Authentication
not needed

2021-02-12 16:34 UTC, halvita approved these changes

2021-02-16 09:07 UTC, SherbaKirill approved these changes

2021-02-21 16:56 UTC, SergeyMokin approved these changes

2021-02-21 17:02 UTC, merged