6.9 Add total story points suggestion
epambrest/capacity pull request #161
Opened 2021-02-22 11:45 UTC by SherbaKirill

2021-02-22 12:13 UTC, SergeyMokin commented on src/Teams.Web/Controllers/ManageSprintsController.cs
> +            var totalSp = sprint.Tasks.Count>0 ? sprint.Tasks.Sum(t => t.StoryPoints) : 0;
spaces?

2021-02-22 12:14 UTC, SergeyMokin commented on src/Teams.Web/Controllers/ManageSprintsController.cs
> +            var sprints = await _manageSprintsService.GetAllSprintsAsync(sprint.TeamId, new DisplayOptions { });
other brackets? { } => ()

2021-02-22 12:15 UTC, SergeyMokin commented on src/Teams.Web/ViewModels/Sprint/SprintViewModel.cs
> +        public string TotalAverageSp { get; set; }
Any benefits of using string?
Not fully clear naming

2021-02-22 12:15 UTC, SergeyMokin commented on src/Teams.Web/Controllers/ManageSprintsController.cs
> +            if (sprints.Count()>0)
please move calculation to service layer

2021-02-22 12:17 UTC, SergeyMokin requested changes

2021-02-22 12:17 UTC, SergeyMokin commented on src/Teams.Web/Controllers/ManageSprintsController.cs
> +            if (sprints.Count()>0)
business logic should be not in this layer.

2021-02-23 09:32 UTC, SergeyMokin commented on src/Teams.Web/Controllers/ManageSprintsController.cs
> +            sprintViewModel.TotalStoryPoint = sprint.Tasks.Count > 0 ? sprint.Tasks.Sum(t => t.StoryPoints) : 0;
in current

2021-02-23 09:32 UTC, SergeyMokin commented on src/Teams.Web/Controllers/ManageSprintsController.cs
> +            sprintViewModel.AverageStoryPoint = await _manageSprintsService.GetAverageStoryPointAsync(sprint);
in completed

2021-02-23 09:33 UTC, SergeyMokin approved these changes

2021-02-23 10:04 UTC, sub13 approved these changes

2021-02-23 12:37 UTC, Y-floryanovich approved these changes

2021-02-27 18:57 UTC, merged