6.5 Add page to compare sprints
epambrest/capacity pull request #183
Opened 2021-02-23 19:26 UTC by aparkhots

#98 
![1](https://user-images.githubusercontent.com/49796195/108896505-12223a80-7626-11eb-9f34-9c03fbd9b137.png)
![2](https://user-images.githubusercontent.com/49796195/108896522-177f8500-7626-11eb-98e6-78b45b74943e.png)
![3](https://user-images.githubusercontent.com/49796195/108896524-18b0b200-7626-11eb-827d-f67e359f3b06.png)

2021-02-23 19:59 UTC, sub13 approved these changes

2021-02-24 15:27 UTC, SergeyMokin requested changes
please add sum of all story points, sum of all tasks, sum of completed tasks, sum of story points of completed tasks

2021-03-23 13:11 UTC, aparkhots commented
![Screenshot_1](https://user-images.githubusercontent.com/49796195/112151522-5d624580-8bf2-11eb-8331-13f0854056cc.png)

2021-03-23 15:09 UTC, Chmelya approved these changes

2021-03-23 15:43 UTC, sub13 approved these changes

2021-03-23 16:05 UTC, SergeyMokin requested changes
add to comparison page requested params

2021-04-01 14:58 UTC, closed without merging