7.5 Remove verification account buttons
epambrest/capacity pull request #192
Opened 2021-03-02 20:31 UTC by Chmelya

Added hidden views. Removed buttons for verify email, phone numbers and two-factor authorization.
Don't touch any logic.

2021-03-04 13:25 UTC, SergeyMokin commented on src/Teams.Web/Areas/Identity/IdentityHostingStartup.cs
> +            builder.ConfigureServices((context, services) => {
single line?

2021-03-04 13:26 UTC, SergeyMokin requested changes
Did you check, is it possible to configure it using setup properties?

2021-03-06 18:07 UTC, Chmelya commented on src/Teams.Web/Areas/Identity/IdentityHostingStartup.cs
> +            builder.ConfigureServices((context, services) => {
generated code

2021-03-07 01:06 UTC, SergeyMokin commented on src/Teams.Web/Areas/Identity/IdentityHostingStartup.cs
> +            builder.ConfigureServices((context, services) => {
alright

2021-03-07 01:06 UTC, SergeyMokin approved these changes

2021-03-07 10:13 UTC, sub13 approved these changes

2021-03-07 12:09 UTC, desenzo approved these changes

2021-03-15 15:48 UTC, merged