7.12 Increase timer of popup
epambrest/capacity pull request #197
Opened 2021-03-07 12:55 UTC by sub13

i increased timer of popup to 5 sec in workingdaysView. If you isn't agree with it, please write down. You can see result in video.
Link to video: https://drive.google.com/file/d/1ayK317-JgDfAjxM1JTYbsJpVL7AhjNJ5/view?usp=sharing

2021-03-08 01:41 UTC, desenzo approved these changes

2021-03-09 07:09 UTC, SergeyMokin requested changes

2021-03-09 07:09 UTC, SergeyMokin commented on src/Teams.Web/Views/ManageMemberWorkingDays/_WorkingDaysPartial.cshtml
> +    <div id="element" class="toast" role="alert" style="position: absolute; top: 0; right: 0;" data-delay="5000">
what about errors popups?
if I remember it happens in other tabs too

2021-03-15 18:15 UTC, Y-floryanovich approved these changes

2021-03-17 09:56 UTC, Chmelya approved these changes

2021-03-19 08:39 UTC, SergeyMokin approved these changes

2021-03-19 09:27 UTC, merged