Hot fix: fixed bug which broke AllsprintsView in our application
epambrest/capacity pull request #199
Opened 2021-03-11 08:57 UTC by sub13

i fixed bug which was breaking our AllsprintsView. This bug was happening when we wanted to check sprints in new Team without sprints. You can see this bug on screenshoot
![изображение](https://user-images.githubusercontent.com/47415747/110761501-db246980-8260-11eb-8724-769d4381c9f2.png)

2021-03-11 12:23 UTC, SergeyMokin approved these changes

2021-03-11 13:50 UTC, SergeyMokin requested changes
Please create issue

2021-03-11 14:20 UTC, sub13 commented
I've created issue, please read one.

2021-03-11 17:47 UTC, desenzo approved these changes

2021-03-14 04:55 UTC, SherbaKirill approved these changes

2021-03-15 18:10 UTC, Y-floryanovich approved these changes

2021-03-17 09:58 UTC, Chmelya approved these changes

2021-03-19 08:40 UTC, SergeyMokin approved these changes

2021-03-19 10:10 UTC, merged