8.2 Install and setup automapper, 8.5 Move repository interface to business layer
epambrest/capacity pull request #240
Opened 2021-04-08 14:45 UTC by sub13

I added and i set automapper up, i little refactored code, i fixed two bug in our program: 1) bug in getSprintById view; 2) bug in alltasksforteamView. If i've done something wrong please write down. I'll try to fix as soon as i can.

2021-04-09 16:28 UTC, SergeyMokin requested changes
Required updates from call

2021-04-12 09:50 UTC, sub13 commented
UPDATE:
I Added Lazy loading into our project, I replaced all repositories to generic one repository, I removed business word, I added Imodel interface with method Update. And i set up tests for these changes

2021-04-12 12:18 UTC, SergeyMokin commented on src/Teams.Data/Repository/IRepository.cs
> +namespace Teams.Data.Repository
Why it is not in Bussiness layer?

2021-04-12 12:23 UTC, SergeyMokin requested changes
Move project dependencies back

2021-04-13 07:53 UTC, SergeyMokin approved these changes

2021-04-13 07:53 UTC, merged