2.3 Remove team
epambrest/capacity pull request #42
Opened 2020-09-25 14:38 UTC by Y-floryanovich

2020-09-25 14:45 UTC, alehkahnovich requested changes

2020-09-25 14:45 UTC, alehkahnovich commented on src/Teams/Controllers/ManageTeamsController.cs
> +            _teamsService.Remove(team_id);
await _teamsService.Remove(team_id);

2020-09-25 14:45 UTC, alehkahnovich commented on src/Teams/Controllers/ManageTeamsController.cs
> +        public void Remove(int team_id)
Is this is an action method? If so then we should return IActionResult or Task<IActionResult>

2020-09-25 14:45 UTC, alehkahnovich commented on src/Teams/Services/IManageTeamsService.cs
> +        Task<bool> Remove(int team_id);
RemoveAsync please, we should stick to naming convention. If the method returns Task then the method name should end with Async

2020-09-25 14:45 UTC, alehkahnovich commented on src/Teams/Services/ManageTeamsService.cs
> +            var team = _teamRepository.GetAll().FirstOrDefault(i => i.TeamOwner == _currentUser.Current.Id() && i.Id == team_id);
There is another version of FirstOrDefaullt extension method, FirstOrDefaulltAsync.

2020-10-05 08:00 UTC, SergeyMokin reviewed
Please resolve conflicts

2020-10-05 08:00 UTC, SergeyMokin commented on Teams.Tests/ManageTeamServiceTest.cs
> +                _currentUser = new CurrentUser(_httpContextAccessor.Object);
please use Mock here

2020-10-05 08:00 UTC, SergeyMokin commented on Teams.Tests/ManageTeamServiceTest.cs
> +                string team_owner = "1234";
can be const

2020-10-05 08:00 UTC, SergeyMokin commented on Teams.Tests/ManageTeamServiceTest.cs
> +                int team_id = 1;
same here

2020-10-05 08:00 UTC, SergeyMokin commented on Teams.Tests/ManageTeamServiceTest.cs
> +             .Returns(new Claim("UserName", team_owner));
please take a look into formatting from 41 line to this

2020-10-05 08:00 UTC, SergeyMokin commented on Teams.Tests/ManageTeamServiceTest.cs
> +            public async Task RemoveAsync_ManageTeamsServiceReturnsFalse_ReturnsFalse()
in this test same questions

2020-10-05 08:14 UTC, alehkahnovich requested changes

2020-10-05 08:14 UTC, alehkahnovich commented on src/Teams/Controllers/ManageTeamsController.cs
> +        public async Task<IActionResult> RemoveAsync(int team_id)
You can skip Async naming convention on endpoint method level as for the methods in controller you should use default naming convention

2020-10-05 12:35 UTC, alehkahnovich approved these changes

2020-10-06 10:42 UTC, merged