2.6 implement get by id member feature
epambrest/capacity pull request #43
Opened 2020-09-29 06:25 UTC by bkmz12353

1. Created **"GetMember(team_id, member_id)"** feature for logged in account in **ManageTeamMembersController** and **ManageTeamMembersService**
   a. Get team member by id can only team member/owner of team_id

2. Covered by tests

2020-09-29 06:44 UTC, alehkahnovich requested changes

2020-09-29 06:44 UTC, alehkahnovich commented on src/Teams/Services/ManageTeamsMembersService.cs
> +        private IRepository<Team, int> _teamRepository;
readonly

2020-09-29 06:44 UTC, alehkahnovich commented on src/Teams/Services/ManageTeamsMembersService.cs
> +           return _teamMemberRepository.GetAll().Where(x => x.MemberId == member_id && x.TeamId == team_id && OwnerOrMemberOfTeam(team_id)).FirstOrDefault();
Is this is a working approach? Did you test this?

2020-09-30 10:40 UTC, SergeyMokin commented on Teams.Tests/MockQueryable/MockQueryable.Core/MockQueryable.Core.csproj
> +﻿<Project Sdk="Microsoft.NET.Sdk">
why you added this project?

2020-09-30 10:41 UTC, SergeyMokin commented on Teams.Tests/MockQueryable/MockQueryable.EntityFrameworkCore/MockQueryable.EntityFrameworkCore.csproj
> +<Project Sdk="Microsoft.NET.Sdk">
also this

2020-09-30 10:41 UTC, SergeyMokin commented on Teams.Tests/MockQueryable/MockQueryable.Moq/MockQueryable.Moq.csproj
> +﻿<Project Sdk="Microsoft.NET.Sdk">
this too

2020-09-30 21:12 UTC, SergeyMokin commented on Teams.Tests/MockQueryableLibs/MoqExtensions.cs
> +namespace MockQueryable.Moq
why you need this?
need just to install package, that is it

2020-09-30 21:12 UTC, SergeyMokin commented on Teams.Tests/MockQueryableLibs/TestAsyncEnumerator.cs
> +namespace MockQueryable.EntityFrameworkCore
Same, remove it

2020-09-30 21:12 UTC, SergeyMokin commented on Teams.Tests/MockQueryableLibs/TestExpressionVisitor.cs
> +	public class TestExpressionVisitor : ExpressionVisitor
this too

2020-09-30 21:12 UTC, SergeyMokin commented on Teams.Tests/MockQueryableLibs/TestQueryProvider.cs
> +namespace MockQueryable.Core
and this

2020-09-30 21:13 UTC, SergeyMokin commented on Teams.Tests/MockQueryableLibs/TestQueryProviderEfCore.cs
> +namespace MockQueryable.EntityFrameworkCore
this too

2020-09-30 21:14 UTC, SergeyMokin commented on Teams.Tests/Teams.Tests.csproj
> +    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="3.1.8" />
here should be reference to MockQueryable.Core and MockQueryable.Moq
First install core

2020-10-02 08:55 UTC, SergeyMokin commented on src/Teams/Controllers/ManageTeamMembersController.cs
> +            if (!_accessCheckService.OwnerOrMemberAsync(team_id).Result)
why Result?

2020-10-02 08:55 UTC, SergeyMokin commented on src/Teams/Controllers/ManageTeamMembersController.cs
> +            if (!_accessCheckService.OwnerOrMemberAsync(team_id).Result)
please read about async/await usage

2020-10-02 08:56 UTC, SergeyMokin commented on src/Teams/Services/IAccessCheckService.cs
> +        public  Task<bool> OwnerOrMemberAsync(int team_id);
public?
compilation error, isn't it?
will be public by default

2020-10-02 08:57 UTC, SergeyMokin commented on src/Teams/Services/IManageTeamsMembersService.cs
> +        public Task<TeamMember> GetMemberAsync(int team_id, string member_id);
same here

2020-10-02 14:03 UTC, SergeyMokin commented on src/Teams/Controllers/ManageTeamMembersController.cs
> +            if (await _accessCheckService.OwnerOrMemberAsync(team_id))
please move this logic to service

2020-10-02 14:07 UTC, SergeyMokin commented on src/Teams/Services/ManageTeamsMembersService.cs
> +             return await _teamMemberRepository.GetAll()
lets see, you created new service which by logic make sense, but you can use here team repository and include team members, get a team with team members and compare result with owner and list of teammembers in team in one go

2020-10-02 14:24 UTC, SergeyMokin approved these changes

2020-10-02 14:56 UTC, alehkahnovich approved these changes

2020-10-02 15:16 UTC, merged