Made 2.1 methods async
epambrest/capacity pull request #44
Opened 2020-10-02 15:42 UTC by bkmz12353

Fix

2020-10-02 15:44 UTC, alehkahnovich approved these changes

2020-10-02 15:44 UTC, alehkahnovich requested changes

2020-10-02 15:44 UTC, alehkahnovich commented on src/Teams/Controllers/ManageTeamsController.cs
> +            return View(_manageTeamsService.GetMyTeamsAsync().Result);
фынтс

2020-10-05 07:53 UTC, SergeyMokin approved these changes

2020-10-05 12:45 UTC, alehkahnovich approved these changes

2020-10-05 12:49 UTC, merged