3.7 implement view for removal team member from team
epambrest/capacity pull request #62
Opened 2020-10-19 15:51 UTC by desenzo

Description
As a customer I want to have an interface to remove team member from team
Solution
1. Implement View for removal team member from team
2. Set Remove button(with icon inside) to remove team member
a. Remove button can see only team owner
b. Removal can not be used for an owner of team
3. Create popup to confirm removal
a. In popup should be shown selected Team_Name and User_Full_Name

2020-10-19 15:52 UTC, desenzo commented
![image](https://user-images.githubusercontent.com/46692099/96475105-4b900700-123c-11eb-9a2f-60a3ad720d83.png)

2020-10-20 07:27 UTC, alehkahnovich requested changes

2020-10-20 07:27 UTC, alehkahnovich commented on src/Teams/Controllers/ManageTeamMembersController.cs
>              ViewBag.Members = members;
Do not use ViewBag try to use direct model instead

2020-10-21 08:44 UTC, SergeyMokin approved these changes

2020-10-21 13:52 UTC, merged