4.6 Implement get by id task feature
epambrest/capacity pull request #73
Opened 2020-11-05 13:09 UTC by Artem-Halvita

2020-11-06 12:50 UTC, SergeyMokin requested changes
Please provide screenshot how view looks like in description of PR

2020-11-06 12:50 UTC, SergeyMokin commented on src/Teams/Controllers/ManageTasksController.cs
> +            if (await _accessCheckService.OwnerOrMemberAsync(teamId))
please invert if statement

2020-11-06 12:50 UTC, SergeyMokin commented on src/Teams/Controllers/ManageTasksController.cs
> +            if (await _accessCheckService.OwnerOrMemberAsync(teamId))
and also else won't be needed
if have no access will be nesting to return error, otherwise correct flow without nesting

2020-11-06 12:50 UTC, alehkahnovich requested changes

2020-11-06 12:50 UTC, alehkahnovich commented on src/Teams/Controllers/ManageTasksController.cs
> +                ViewBag.TaskName = task.Name;
Please avoid using ViewBag, use models instead

2020-11-06 12:50 UTC, alehkahnovich commented on src/Teams/Controllers/ManageTasksController.cs
> +            else
Is else is really need here?

2020-11-09 12:44 UTC, SergeyMokin commented on Teams.Tests/ManageTasksServiceTest.cs
> +    [SetUp]
take a look into tabulation

2020-11-09 12:45 UTC, SergeyMokin commented on Teams.Tests/ManageTasksServiceTest.cs
> +            _taskReposotiry.Setup(x => x.GetByIdAsync(It.IsAny<int>())).ReturnsAsync(task.FirstOrDefault());
do you need it?

2020-11-09 12:45 UTC, SergeyMokin commented on src/Teams/Controllers/ManageTasksController.cs
> +        private readonly IAccessCheckService _accessCheckService;
well, why you inject it but not use?

2020-11-09 12:46 UTC, SergeyMokin commented on src/Teams/Controllers/ManageTasksController.cs
> +            var task = await _manageTasksService.GetTaskByIdAsync(taskId);
I asked to invert IF statement, not remove

2020-11-10 15:40 UTC, SergeyMokin approved these changes

2020-11-10 17:26 UTC, merged