4.5 Implement get all tasks feature (for team)
epambrest/capacity pull request #74
Opened 2020-11-05 22:21 UTC by desenzo

Description
As a developer I want to have possibility to get all tasks for the team
and to get all tasks for the sprint.
Solution
Create service, controller and view to get all tasks for the team
and for the sprint.

2020-11-05 22:23 UTC, desenzo commented
![image](https://user-images.githubusercontent.com/46692099/98303011-7e712380-1fce-11eb-858f-716dbf717d83.png)
In team
![image](https://user-images.githubusercontent.com/46692099/98303029-892bb880-1fce-11eb-8d14-3280d13c97bb.png)
in sprint 
![image](https://user-images.githubusercontent.com/46692099/98303081-9b0d5b80-1fce-11eb-9fd3-c293b8579e1c.png)

2020-11-06 12:45 UTC, SergeyMokin requested changes
Please correct the comments

2020-11-06 12:45 UTC, SergeyMokin commented on Teams.Tests/ManageTasksServiceTest.cs
> +        public async System.Threading.Tasks.Task GetAllTasksInTeamAsyncReturnListTasks_ReturnListTasks()
Forget in names one _ symbol, also bit weird naming
Should be: GetAllTasksInTeamAsync_RepositoryContainsTwoTasksForSelectedTeam_ReturnsTwoTasks

Also name of executed method: GetMyTaskInTeamAsync, better to use GetAllTasksForTeam

2020-11-06 12:45 UTC, SergeyMokin commented on src/Teams/Controllers/ManageSprintsController.cs
> +            if (sprint == null)
please remove not needed changes

2020-11-06 12:45 UTC, SergeyMokin commented on src/Teams/Controllers/ManageSprintsController.cs
> +
also here

2020-11-06 12:45 UTC, SergeyMokin commented on Teams.Tests/ManageTasksServiceTest.cs
> +            int team_id = 1;
also, I missed it before, but better to use not snake case, please read doc here: https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/inside-a-program/coding-conventions

should be teamId, here a lot of places to change.

snake case fine to use with consts, enum values. names for tests

2020-11-06 12:45 UTC, SergeyMokin commented on Teams.Tests/ManageTasksServiceTest.cs
> +            int team_id = 1;
please take a look into it

2020-11-06 12:45 UTC, SergeyMokin commented on src/Teams/Controllers/ManageTasksController.cs
> +            if (await _accessCheckService.OwnerOrMemberAsync(team_id))
better to use less nesting.
please invert if statement, also you don't need "else" at all.
will be more readable

2020-11-06 12:45 UTC, SergeyMokin commented on src/Teams/Services/IManageTasksService.cs
> +        Task<IEnumerable<Models.Task>> GetMyTaskInTeamAsync(int team_id, DisplayOptions options);
Please use different names.
Please take a look into tests comments.

2020-11-06 12:45 UTC, SergeyMokin commented on src/Teams/Services/ManageSprintsService.cs
> +            var sprints = _sprintRepository.GetAll().Include(x => x.Team).Include(x=>x.Tasks).Where(x => x.TeamId == team_id);
Do you always need tasts included?
Maybe better to propose here bool option to include it or not?

2020-11-06 12:45 UTC, SergeyMokin commented on src/Teams/Services/ManageSprintsService.cs
> +        public async Task<Sprint> GetSprintAsyncw(int sprint_id)
typo Asyncw

2020-11-06 12:45 UTC, SergeyMokin commented on src/Teams/Views/ManageSprints/GetSprintById.cshtml
> +        <td align="left" style="border-top: hidden; font-weight: bold">Store Point</td>
typo: should be Story

2020-11-06 12:49 UTC, alehkahnovich requested changes

2020-11-06 12:49 UTC, alehkahnovich commented on src/Teams/Controllers/ManageTasksController.cs
> +                ViewBag.TeamName = team.TeamName;
Please avoid using ViewBag, use model instead

2020-11-11 08:57 UTC, SergeyMokin commented
conflicts

2020-11-11 09:02 UTC, SergeyMokin commented on src/Teams/Controllers/ManageSprintsController.cs
> +            var sprint = await _manageSprintsService.GetSprintAsync(sprint_id,true);
please change snake case where you working to camel

2020-11-11 09:02 UTC, SergeyMokin commented on src/Teams/Controllers/ManageTasksController.cs
> +        public async Task<IActionResult> AllTasksForTeam(int team_id, DisplayOptions options)
team_id

2020-11-11 09:03 UTC, SergeyMokin commented on src/Teams/Services/IManageSprintsService.cs
> +        Task<Sprint> GetSprintAsync(int sprint_id, bool includeTaskAndTeamMember);
sprint_id

2020-11-11 09:03 UTC, SergeyMokin commented on src/Teams/Services/IManageTasksService.cs
> +        Task<IEnumerable<Models.Task>> GetAllTasksForTeamAsync(int team_id, DisplayOptions options);
team_id

2020-11-11 09:03 UTC, SergeyMokin commented on src/Teams/Services/ManageSprintsService.cs
> +        public async Task<Sprint> GetSprintAsync(int sprint_id, bool includeTaskAndTeamMember)
sprint_id

2020-11-11 09:05 UTC, SergeyMokin commented on src/Teams/Views/ManageSprints/GetSprintById.cshtml
> +        <td align="left" style="border-top: hidden; font-weight: bold">Store Point</td>
Store Point

2020-11-11 09:05 UTC, SergeyMokin commented on src/Teams/Views/ManageTasks/AllTasksForTeam.cshtml
> +        <td align="left" style="border-top: hidden; font-weight: bold">Store Point</td>
store point

2020-11-11 15:48 UTC, SergeyMokin commented
please fix conflicts

2020-11-13 09:48 UTC, SergeyMokin approved these changes

2020-11-13 11:05 UTC, merged