4.13 Typo in model Sprint description
epambrest/capacity pull request #78
Opened 2020-11-10 17:48 UTC by desenzo

### Description
As a developer i dont want to see typo in our models.
When describing the model Sprint.An error was made in the property "StorePointInHours",
but right "StoryPointtInHours.

### Solution
Find and fix all related typos related to this.

2020-11-10 18:00 UTC, bkmz12353 requested changes

2020-11-10 18:00 UTC, bkmz12353 commented on src/Teams/Views/ManageSprints/AllSprints.cshtml
>      </table>
remove -s

2020-11-10 18:02 UTC, bkmz12353 approved these changes

2020-11-11 08:55 UTC, SergeyMokin approved these changes

2020-11-11 14:14 UTC, merged